version: "3.8"

services:
  fastapi:
    build:
      context: .
      dockerfile: fastapi/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    volumes:
      - reports:/app/reports

  celery-worker:
    build:
      context: .
      dockerfile: celery/Dockerfile
    depends_on:
      - rabbitmq
    volumes:
      - reports:/app/reports

  flower:
    build:
      context: .
      dockerfile: flower/Dockerfile
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3.8"
    ports:
      - "5672:5672"

volumes:
  reports:
